server:
  port: 8088
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:log4jdbc:h2:mem:jpademo;MODE=MySQL;DATABASE_TO_LOWER=TRUE;
    username: root
    password: root
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  h2:
    console:
      enabled: true
      path: /h2